### ISSUE TITLE
Your Podfile requires that the plugin `cocoapods-bugsnag` be installed.

### ISSUE THREAD

**Issue by PoulsQ** [bugsnag/cocoapods-bugsnag#21] opened 2020-11-30 09:04 UTC
Hello guys,

I'm having troubles installing it with POD.
In my React-Native project, I'm runned : `cd ios/ && gem install cocoapods-bugsnag`

My return was:
```
Successfully installed cocoapods-bugsnag-2.2.1
Parsing documentation for cocoapods-bugsnag-2.2.1
Done installing documentation for cocoapods-bugsnag after 0 seconds
1 gem installed
```

Then I added to my Podfile:
```
pod 'Bugsnag'
plugin 'cocoapods-bugsnag'
```

But when I'm running: `pod install`
I've this error :  
```
[!] Your Podfile requires that the plugin `cocoapods-bugsnag` be installed. Please install it and try installation again.
```
and the installation stop... 

Could someone help me pls ?

**Comment by PoulsQ** [comment] 2020-12-01 08:03
Ok, I made a manual installation, it seems to be working fine.
Maybe you should check the CocoaPods process!

**Comment by MrShakes** [comment] 2020-12-16 20:36
@PoulsQ same issue here

**Comment by mattdyoung** [comment] 2020-12-18 12:56
Re-opening and we'll try to reproduce this to see what the issue might be.

**Comment by xljones** [comment] 2020-12-21 12:43
@PoulsQ @MrShakes From the location you are running `pod ...` where your `Podfile` should be, please can you run the following two commands and let us know the full output of both?
```
$ ruby -v
```
and then
```
$ pod env
```

**Comment by MrShakes** [comment] 2020-12-22 07:11
ruby -v
```
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```
pod env

/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/cdn_source.rb:342: warning: URI.escape is obsolete

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin18]
    RubyGems : 3.1.4
        Host : Mac OS X 10.14.5 (18F2059)
       Xcode : 11.2.1 (11B53)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /usr/local/Cellar/ruby/2.7.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

plugin 'cocoapods-bugsnag'

target 'YYY' do
  # Pods for YYY

  pod 'Bugsnag'

  # Aditional Pods - 2018-04-10
  # pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_native_modules!

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
end
```

**Comment by xljones** [comment] 2020-12-22 16:16
Hey @MrShakes, looks like your Ruby version (`2.3.7p456`) doesn't match that which your CocoaPods environment is using (`2.7.2p137`), so when you install the plugin, it's not being seen by CocoaPods.

Not sure of your entire environment setup, but are you're using a Ruby environment switcher like `rbenv`? If so, you may need to shim your environment with `$ rbenv rehash` (https://github.com/rbenv/rbenv#rbenv-rehash)

Alternatively, you could switch your Ruby environment to match the version that CocoaPods is using and then install `cocoapods-bugsnag` from there. Then, CocoaPods will be able to use this plugin.

**Comment by MrShakes** [comment] 2020-12-26 14:42
@xander-jones I already switched over to using the manual build phase, thanks for the help though

**Comment by xljones** [comment] 2021-01-04 18:24
No worries, closing this issue out as it appears to be a Ruby versioning issue, not an issue with `cocoapods-bugsnag` itself.

**Closed as completed by xljones** 2021-01-04 18:24 UTC

**Comment by rousseau634** [comment] 2021-04-20 07:55
@xander-jones Hey, I got same issues but is occur when I send bitrise .


$ pod "_1.10.1_" "install"
[!] Your Podfile requires that the plugin `cocoapods-bugsnag` be installed. Please install it and try installation again.
Command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | cocoapods-install@2.1 (exit code: 1)                          | 2.8 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-cocoapods-install/issues  |
| Source: https://github.com/bitrise-io/steps-cocoapods-install                |
+---+---------------------------------------------------------------+----------+

**Comment by xljones** [comment] 2021-04-20 12:50
Hey @rousseau634, looks like you're using Bitrise's CocoaPods install step here, I can see that you've raised https://github.com/bitrise-steplib/steps-cocoapods-install/issues/66 too, so will keep an eye on this too.

Have you first installed the plugin into the same environment from which `pod` is operating? This will be a step that needs to be completed prior to the call to `pod install`

The docs for this plugin can be found here: https://docs.bugsnag.com/platforms/ios/symbolication-guide/#using-cocoapods-plugin

**Comment by objectiveSee** [comment] 2022-03-05 21:11
Same issue, seems like the best way to resolve this is remove Bug-snag from your project and use a different service.

**Comment by Pandazaur** [comment] 2022-05-09 10:00
Same issue happened when I tried to upgrade to the last react native version. I've updated cocoapoads from v10 to v11 and could not `pod install` anymore.

If you have a `Gemfile` at the project's root. Try to add this inside:
```
gem 'cocoapods-bugsnag'
```

Working fine here

**Comment by Shmublon** [comment] 2023-09-27 19:07
hello, help! I have the same issue, nothing helps! I have m1

**Comment by mclack** [comment] 2023-10-03 13:14
Hi @Shmublon 

We’ve become aware of certain compatibility problems that Apple M1 chips have, which can interfere with the pod install function used when building Cocoa apps. I’ve outlined a potential solution below which has worked for us in the past:

- If you don’t have it already, install [Homebrew](https://brew.sh/) and use it to install Cocoapods:
`brew install cocoapods`

- Once Cocoapods is installed, return to your home directory (open a new terminal) and run:
`sudo arch -x86_64 gem install ffi`

- When this is finished, return to the the iOS project directory and run:
`pod install`

- If this does not work or results in an error try:
`arch -x86_64 pod install`

- If either pod install method works, try building the app and see what happens.

The following GitHub issue provided this resolution, for context: https://github.com/CocoaPods/CocoaPods/issues/10518

If you have tried all the recommendations as suggested on this thread and [here](https://github.com/bugsnag/cocoapods-bugsnag/issues/27), then can you please create a support ticket with us by contact [support@bugsnag.com](mailto:support@bugsnag.com), and provide a summary of the steps you have taken to [install the plugin](https://docs.bugsnag.com/platforms/ios/showing-full-stacktraces/#using-cocoapods-plugin). It would also be useful for you to let us know the outputs when you run `ruby -v` and `pod env`.
